### ISSUE TITLE
Linter failed on invalid source file .vue

### ISSUE THREAD

**Issue by tahq69** [prograhammer/vscode-tslint-vue#3] opened 2017-11-25 11:21 UTC
Installed 1.3.0
Have a local version of `tslint` and `typescript`
Lintings throws a traceback:
```
[Info  - 13:05:46] Linter is running.
[Info  - 13:05:47] TSLint library loaded from: d:\Code\tahq69\competition-manager-ui\node_modules\tslint\lib\index.js
[Info  - 13:05:47] vscode-tslint: '
Invalid source file: d:\Code\tahq69\competition-manager-ui\src\Components\Forms\FormGroup.vue. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.
                ' while validating: d:\Code\tahq69\competition-manager-ui\src\Components\Forms\FormGroup.vue stacktrace: FatalError: 
Invalid source file: d:\Code\tahq69\competition-manager-ui\src\Components\Forms\FormGroup.vue. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.
                
    at new FatalError (d:\Code\tahq69\competition-manager-ui\node_modules\tslint\lib\error.js:27:28)
    at Linter.getSourceFile (d:\Code\tahq69\competition-manager-ui\node_modules\tslint\lib\linter.js:202:23)
    at Linter.lint (d:\Code\tahq69\competition-manager-ui\node_modules\tslint\lib\linter.js:72:31)
    at C:\Users\user\.vscode\extensions\prograhammer.tslint-vue-1.3.0\server\server.js:426:24
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\.vscode\extensions\prograhammer.tslint-vue-1.3.0\server\server.js:7:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Same as issue #1 , but on windows it is not fixed

Repository where I try to add linting: https://github.com/tahq69/competition-manager-ui

**Comment by prograhammer** [comment] 2017-11-25 12:37
It looks like you have specified an include pattern that only picks up on `.ts`. Update your include in `tsconfig.json` to be `"src/**/*"` or add `"src/**/*.vue"`. Something like this:

```
  "include": [
    "src/**/*.ts",
    "src/**/*.vue"
  ],
  "exclude": [
      "node_modules"
  ],
```
Then restart VSCode.

**Comment by tahq69** [comment] 2017-11-26 11:06
Cool, that helped out, but now I got more issues:
1) Placing script section after template leads to line mismatch in linter:
![image](https://user-images.githubusercontent.com/7248215/33239406-5d36d576-d2aa-11e7-8e46-80b727208602.png)
2) Enabling tslint.typeCheck leads to parsing whole vue file:
![image](https://user-images.githubusercontent.com/7248215/33239316-e594b18e-d2a7-11e7-82e9-ac87a33bf42a.png)

**Comment by aweiu** [comment] 2017-11-28 12:27
@tahq69 Enabling tslint.typeCheck leads to parsing whole vue file,me too!

**Comment by prograhammer** [comment] 2017-11-29 00:07
I think this is a Windows issue. @tahq69 Are you on Windows as well?

I applied a bug fix to normalize the slashes in some paths. Please try in latest version (v1.3.5). Uninstall and reinstall to get latest. 

I also included some debug info. So if the problem isn't fixed, then bring up your output tab (View > Output). There's a drop down on the far right of that tab, select `tslint` in that dropdown so that it filters output from tslint. Now navigate to a `.vue` file. Now close all other tabs, then close VSCode editor completely and then reopen. This will ensure the output is minimal (swtich back to `tslint` if needed). Now copy/paste all that output here. Let's see if the file paths look right. Otherwise I won't be able to test Windows until later in the week.

**Comment by aweiu** [comment] 2017-11-29 01:55
@prograhammer I am on Mac Os.If i enable tslint.typeCheck,it will be:
![1511920307171](https://user-images.githubusercontent.com/15623620/33353935-421e8caa-d4eb-11e7-8489-4e9159ab51cd.jpg)

**Comment by prograhammer** [comment] 2017-11-29 02:14
@aweiu 

I need the output logs. Paste the text from the "output" tab. From the menu `View > Output` and select `tslint` in the drop down filter of the output tab. Then copy/paste that here. (make sure you are on a .vue file when you do this).

**Comment by aweiu** [comment] 2017-11-29 02:24
```
[Info  - 10:24:11] Linter is running.
[Info  - 10:24:12] TSLint library loaded from: /Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint/lib/index.js
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/src/App.vue
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/src/main.ts
containing file: /Users/aweiu/Documents/工作/yun-game-admin/src/main.ts
module before: ./App.vue
module relative1: /Users/aweiu/Documents/工作/yun-game-admin/src/App.vue
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/node_modules/vue/types/index.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/node_modules/vue/types/vue.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/node_modules/vue/types/options.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/node_modules/vue/types/vnode.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/node_modules/vue/types/plugin.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/src/router/index.ts
containing file: /Users/aweiu/Documents/工作/yun-game-admin/src/router/index.ts
module before: ../components/Index.vue
module relative2: /Users/aweiu/Documents/工作/yun-game-admin/src/components/Index.vue
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/node_modules/vue-router/types/index.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/node_modules/vue-router/types/vue.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/node_modules/vue-router/types/router.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/src/components/Index.vue
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/Documents/工作/yun-game-admin/src/vue-shims.d.ts
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/.vscode/extensions/prograhammer.tslint-vue-1.3.5/server/node_modules/typescript/lib/lib.es2017.d.ts
filename: /Users/aweiu/.vscode/extensions/prograhammer.tslint-vue-1.3.5/server/node_modules/typescript/lib/lib.es2017.d.ts
undefined!!!!!!!!!!
FILES FIX: file:///Users/aweiu/Documents/%E5%B7%A5%E4%BD%9C/yun-game-admin/src/components/Index.vue /Users/aweiu/.vscode/extensions/prograhammer.tslint-vue-1.3.5/server/node_modules/typescript/lib/lib.dom.d.ts
filename: /Users/aweiu/.vscode/extensions/prograhammer.tslint-vue-1.3.5/server/node_modules/typescript/lib/lib.dom.d.ts
undefined!!!!!!!!!!
TypeError: Cannot read property '1' of null
    at ObjectCurlySpacingWalker.checkSpacingInsideBraces (/Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint-eslint-rules/dist/rules/objectCurlySpacingRule.js:54:54)
    at ObjectCurlySpacingWalker.visitNode (/Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint-eslint-rules/dist/rules/objectCurlySpacingRule.js:44:18)
    at /Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (/Users/aweiu/Documents/工作/yun-game-admin/node_modules/typescript/lib/typescript.js:12634:24)
    at Object.forEachChild (/Users/aweiu/Documents/工作/yun-game-admin/node_modules/typescript/lib/typescript.js:12780:21)
    at ObjectCurlySpacingWalker.SyntaxWalker.walkChildren (/Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at ObjectCurlySpacingWalker.SyntaxWalker.visitTypeAssertionExpression (/Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint/lib/language/walker/syntaxWalker.js:252:14)
    at ObjectCurlySpacingWalker.SyntaxWalker.visitNode (/Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint/lib/language/walker/syntaxWalker.js:506:22)
    at ObjectCurlySpacingWalker.visitNode (/Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint-eslint-rules/dist/rules/objectCurlySpacingRule.js:46:36)
    at /Users/aweiu/Documents/工作/yun-game-admin/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63

```

**Comment by prograhammer** [comment] 2017-11-29 05:10
@aweiu I see the problem. Working on a fix right now.

@tahq69 Can you get me a copy of this from your Windows machine as well?

**Comment by prograhammer** [comment] 2017-11-29 06:45
@aweiu Your problem should be fixed now in latest (v1.3.6). Uninstall, reload, install.

**Comment by aweiu** [comment] 2017-11-29 07:07
@prograhammer Good job!Thanks!But,as you see,i use the vue data "msg"  in html template,but the type check will warn "unused variable",how to resolve it?

**Comment by aweiu** [comment] 2017-11-29 07:10
@prograhammer Maybe,the only way is:
`// tslint:disable-next-line:no-unused-variable`

**Comment by prograhammer** [comment] 2017-11-29 07:19
No, I think it's because you declared it private and didn't use it internally (other than the template). So remove the `private` scope. If you add the @Component decorator, then that's where public props are handled. It would be nice to still mark them private so they don't show up when referencing the module in other modules in autocomplete popup box. I'll have to think more about this one. Maybe post it on stackoverflow and include the link here so I can answer on stackoverflow if I have time to look into it.

**Comment by tahq69** [comment] 2017-11-29 07:41
Yes, I am on Windows
Current version: 1.3.6
```
[Info  - 09:37:30] Linter is running.
[Info  - 09:37:31] TSLint library loaded from: c:\Projects\TAHQ69\GIT\vue-select\node_modules\tslint\lib\index.js
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/src/Contracts.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/src/main.ts
containing file: c:/Projects/TAHQ69/GIT/vue-select/src/main.ts
module before: ./Select.vue
module relative1: c:/Projects/TAHQ69/GIT/vue-select/src/Select.vue
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue/types/index.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue/types/vue.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue/types/options.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue/types/vnode.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue/types/plugin.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/src/Select.vue
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue-class-component/lib/index.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue-class-component/lib/declarations.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue-class-component/lib/util.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/vue-property-decorator/lib/vue-property-decorator.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/node_modules/reflect-metadata/index.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/src/Vue-shim.d.ts
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/src/example/Example.vue
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue c:/Projects/TAHQ69/GIT/vue-select/src/example/main.ts
containing file: c:/Projects/TAHQ69/GIT/vue-select/src/example/main.ts
module before: ./Example.vue
module relative1: c:/Projects/TAHQ69/GIT/vue-select/src/example/Example.vue
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue C:/Users/IgorsK/.vscode/extensions/prograhammer.tslint-vue-1.3.6/server/node_modules/typescript/lib/lib.dom.d.ts
filename: C:/Users/IgorsK/.vscode/extensions/prograhammer.tslint-vue-1.3.6/server/node_modules/typescript/lib/lib.dom.d.ts
undefined!!!!!!!!!!
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue C:/Users/IgorsK/.vscode/extensions/prograhammer.tslint-vue-1.3.6/server/node_modules/typescript/lib/lib.es5.d.ts
filename: C:/Users/IgorsK/.vscode/extensions/prograhammer.tslint-vue-1.3.6/server/node_modules/typescript/lib/lib.es5.d.ts
undefined!!!!!!!!!!
FILES FIX: file:///c%3A/Projects/TAHQ69/GIT/vue-select/src/Select.vue C:/Users/IgorsK/.vscode/extensions/prograhammer.tslint-vue-1.3.6/server/node_modules/typescript/lib/lib.es2015.d.ts
filename: C:/Users/IgorsK/.vscode/extensions/prograhammer.tslint-vue-1.3.6/server/node_modules/typescript/lib/lib.es2015.d.ts
undefined!!!!!!!!!!
```

**Comment by prograhammer** [comment] 2017-11-29 09:08
@tahq69 There was a problem with Windows paths encoding colons `:` which it should not do. It is fixed now. Install v1.3.7.

Thanks!

**Comment by tahq69** [comment] 2017-11-29 10:30
@prograhammer Cool, now it works for me too.

What about linter line mismatch mentioned at [this comment](https://github.com/prograhammer/vscode-tslint-vue/issues/3#issuecomment-347000420)?

I am used to place template at top of the file (And VueJs guide says it is ok while all files are same), but error location is really annoying... It appears when there is blank lines in template or between template and script tag.

![image](https://user-images.githubusercontent.com/7248215/33370673-f0a650a4-d500-11e7-80d0-1c026ca6b297.png)
2 blank lines leads to mismatch in two lines

**Comment by prograhammer** [comment] 2017-11-29 10:45
Now that's a much stranger issue. I'll take a look in the morning. I may send up another patch version with extra debugging output for you to copy/paste again.

**Comment by prograhammer** [comment] 2017-11-30 12:05
@tahq69 

Ok, let's look at what is being parsed. First install latest (v1.3.9). Then navigate to your home directory in Windows, or search for the folder `.vscode/extensions/prograhammer.tslint-vue-1.3.9` and go to the file `server/server.js`. Add the following below line 378: 

    console.log('Contents ***************************************');
    console.log(contents);

Now put your template above your script where your error line numbers mess up (like you show in the previous post) and then look at the output window. Copy/paste that output here.

**Comment by tahq69** [comment] 2017-11-30 13:18
@prograhammer 

The result is below:
![image](https://user-images.githubusercontent.com/7248215/33432419-7ebb6f20-d5e0-11e7-82cc-9f81908e25c8.png)

I noticed in one other project everything is ok, because I added .gitattributes file and decleader `text eol=lf`

![image](https://user-images.githubusercontent.com/7248215/33432521-f2d64c2c-d5e0-11e7-8cdf-d12165055ffa.png)

It means that content gets 2 comment lines on windows single crlf linebreak;

**Comment by prograhammer** [comment] 2017-12-01 11:24
@tahq69 It should work now in both LF or CRLF. Update to latest v1.4.0.

Thanks!

**Comment by tahq69** [comment] 2017-12-03 08:27
@prograhammer it is, thanks :)

**Closed** 2017-12-03 08:41 UTC
